/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7ac1c9937ba04bc567989591ad6ca77e)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	GAME: DurableObjectNamespace<import("./src/worker").GameRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "GameRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
